Note that HMR requires the bounding box of the person in the image. The best performance is obtained when max length of the person in the image is roughly 150px.

When only the image path is supplied, it assumes that the image is centered on a person whose length is roughly 150px.

Alternatively, you can supply output of the openpose to figure out the bbox and the right scale factor.

Sample usage:

In [1]:
# # On images on a tightly cropped image around the person
# python -m demo --img_path data/im1963.jpg
# python -m demo --img_path data/coco1.png

# # On images, with openpose output
# python -m demo --img_path data/random.jpg --json_path data/random_keypoints.json

In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys
from absl import flags
import numpy as np

import skimage.io as io
import tensorflow as tf

from src.util import renderer as vis_util
from src.util import image as img_util
from src.util import openpose as op_util
import src.config
from src.RunModel import RunModel

In [3]:
flags.DEFINE_string('img_path', 'data/im1963.jpg', 'Image to run')
flags.DEFINE_string(
    'json_path', None,
    'If specified, uses the openpose output to crop the image.')

In [4]:
# def visualize(img, proc_param, joints, verts, cam):
#     """
#     Renders the result in original image coordinate frame.
#     """
#     cam_for_render, vert_shifted, joints_orig = vis_util.get_original(
#         proc_param, verts, cam, joints, img_size=img.shape[:2])

#     # Render results
#     skel_img = vis_util.draw_skeleton(img, joints_orig)
#     rend_img_overlay = renderer(
#         vert_shifted, cam=cam_for_render, img=img, do_alpha=True)
#     rend_img = renderer(
#         vert_shifted, cam=cam_for_render, img_size=img.shape[:2])
#     rend_img_vp1 = renderer.rotated(
#         vert_shifted, 60, cam=cam_for_render, img_size=img.shape[:2])
#     rend_img_vp2 = renderer.rotated(
#         vert_shifted, -60, cam=cam_for_render, img_size=img.shape[:2])

#     import matplotlib.pyplot as plt
#     # plt.ion()
#     plt.figure(1)
#     plt.clf()
#     plt.subplot(231)
#     plt.imshow(img)
#     plt.title('input')
#     plt.axis('off')
#     plt.subplot(232)
#     plt.imshow(skel_img)
#     plt.title('joint projection')
#     plt.axis('off')
#     plt.subplot(233)
#     plt.imshow(rend_img_overlay)
#     plt.title('3D Mesh overlay')
#     plt.axis('off')
#     plt.subplot(234)
#     plt.imshow(rend_img)
#     plt.title('3D mesh')
#     plt.axis('off')
#     plt.subplot(235)
#     plt.imshow(rend_img_vp1)
#     plt.title('diff vp')
#     plt.axis('off')
#     plt.subplot(236)
#     plt.imshow(rend_img_vp2)
#     plt.title('diff vp')
#     plt.axis('off')
#     plt.draw()
#     plt.show()
#     # import ipdb
#     # ipdb.set_trace()

In [5]:
def preprocess_image(img_path, json_path=None):
    img = io.imread(img_path)
    if img.shape[2] == 4:
        img = img[:, :, :3]

    if json_path is None:
        if np.max(img.shape[:2]) != config.img_size:
            print('Resizing so the max image size is %d..' % config.img_size)
            scale = (float(config.img_size) / np.max(img.shape[:2]))
        else:
            scale = 1.
        center = np.round(np.array(img.shape[:2]) / 2).astype(int)
        # image center in (x,y)
        center = center[::-1]
    else:
        scale, center = op_util.get_bbox(json_path)

    crop, proc_param = img_util.scale_and_crop(img, scale, center,
                                               config.img_size)

    # Normalize image to [-1, 1]
    crop = 2 * ((crop / 255.) - 0.5)

    return crop, proc_param, img

In [6]:
config = flags.FLAGS

In [7]:
remaining_args = config([sys.argv[0]] + [flag for flag in sys.argv if flag.startswith("--")])
assert(remaining_args == [sys.argv[0]])

In [8]:
# config(sys.argv)

In [9]:
# Using pre-trained model, change this to use your own.
config.load_path = src.config.PRETRAINED_MODEL

config.batch_size = 1

# renderer = vis_util.SMPLRenderer(face_path=config.smpl_face_path)

# main(config.img_path, config.json_path)


In [10]:
# def main(img_path, json_path=None):
img_path=config.img_path
json_path=config.json_path
sess = tf.Session()
model = RunModel(config, sess=sess)

W0227 23:23:30.704256 13820 deprecation_wrapper.py:119] From C:\_Files\MyProjects\ASDS_3\Photo_Wake-Up\src\HMR\TensorFlow\src\RunModel.py:42: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0227 23:23:33.047132 13820 deprecation_wrapper.py:119] From C:\_Files\MyProjects\ASDS_3\Photo_Wake-Up\src\HMR\TensorFlow\src\models.py:77: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.



Iteration 0


W0227 23:23:33.413739 13820 deprecation.py:323] From C:\_Files\MyProjects\ASDS_3\Photo_Wake-Up\src\HMR\TensorFlow\src\tf_smpl\batch_lbs.py:55: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


Iteration 1
Reuse is on!
Iteration 2
Reuse is on!


W0227 23:23:34.473660 13820 deprecation_wrapper.py:119] From C:\_Files\MyProjects\ASDS_3\Photo_Wake-Up\src\HMR\TensorFlow\src\RunModel.py:70: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0227 23:23:34.660108 13820 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


Restoring checkpoint C:\_Files\MyProjects\ASDS_3\Photo_Wake-Up\src\HMR\TensorFlow\src\..\models\model.ckpt-667589..


In [11]:
input_img, proc_param, img = preprocess_image(img_path, json_path)
# Add batch dimension: 1 x D x D x 3
input_img = np.expand_dims(input_img, 0)

# Theta is the 85D vector holding [camera, pose, shape]
# where camera is 3D [s, tx, ty]
# pose is 72D vector holding the rotation of 24 joints of SMPL in axis angle format
# shape is 10D shape coefficients of SMPL
joints, verts, cams, joints3d, theta = model.predict(
    input_img, get_theta=True)

# visualize(img, proc_param, joints[0], verts[0], cams[0])

Resizing so the max image size is 224..


In [12]:
print('proc params: ', proc_param)
print('joints: ', joints[0])
print('vertices; ', verts[0])
print('cameras: ', cams[0])
print('theta: ', theta)

proc params:  {'scale': 1.4088050314465408, 'start_pt': array([112,  68]), 'end_pt': array([336, 292]), 'img_size': 224}
joints:  [[ 32.06795  140.72649 ]
 [ 73.78502  113.38104 ]
 [103.38444   72.01409 ]
 [109.91133   73.48858 ]
 [ 83.33781  115.9165  ]
 [ 41.370445 142.30145 ]
 [175.27367  143.25969 ]
 [165.14287  112.649704]
 [161.22424   80.32551 ]
 [159.80148   77.228546]
 [154.78026  108.06112 ]
 [168.35434  135.01814 ]
 [165.64624   77.28819 ]
 [190.89182   79.25426 ]
 [179.96492   90.47428 ]
 [184.19102   84.35532 ]
 [184.7576    90.15795 ]
 [181.67886   73.14963 ]
 [182.66008   85.88108 ]]
vertices;  [[ 0.71302354 -0.18414527  0.10629456]
 [ 0.69966346 -0.17387116  0.10655451]
 [ 0.6944859  -0.1877892   0.10817218]
 ...
 [ 0.6645237  -0.15919268 -0.05238074]
 [ 0.66643304 -0.15805858 -0.05126441]
 [ 0.66423136 -0.15391274 -0.05141819]]
cameras:  [ 1.0587609  -0.05779588 -0.06080284]
theta:  [[ 1.05876088e+00 -5.77958822e-02 -6.08028397e-02  2.87064052e+00
   1.47014046e+00  2.

In [13]:
print('shape of joints: ', joints[0].shape)
print('shape of 3D joints: ', joints3d[0].shape)
print('shape of vertices; ', verts[0].shape)
print('shape of cameras: ', cams[0].shape)
print('shape of theta: ', theta[0].shape)

shape of joints:  (19, 2)
shape of 3D joints:  (19, 3)
shape of vertices;  (6890, 3)
shape of cameras:  (3,)
shape of theta:  (85,)


In [14]:
print('overall shape of joints: ', joints.shape)
print('overall shape of 3D joints: ', joints3d.shape)
print('overall shape of vertices; ', verts.shape)
print('overall shape of cameras: ', cams.shape)
print('overall shape of theta: ', theta.shape)

overall shape of joints:  (1, 19, 2)
overall shape of 3D joints:  (1, 19, 3)
overall shape of vertices;  (1, 6890, 3)
overall shape of cameras:  (1, 3)
overall shape of theta:  (1, 85)
