In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time
import cv2
%matplotlib inline

In [2]:
path = 'photo\p0\\'

corresponding_in = np.load(path+'small_corresponding_in.npy')
# corresponding_in = np.load(path+'tps_small_corresponding_in.npy')

lis =np.load(path+'small_corresponding_contours.npy')
data1 = np.load(path+'small_contours.npy')
data2 = np.load(path+'small_contours_smpl.npy')

In [3]:
for i in corresponding_in:
    print(i)

[[28 22]
 [29 22]]
[[28 23]
 [28 23]]
[[29 20]
 [30 21]]
[[29 21]
 [30 22]]
[[29 22]
 [30 23]]
[[29 23]
 [29 23]]
[[29 24]
 [28 23]]
[[30 20]
 [31 22]]
[[30 21]
 [31 23]]
[[30 22]
 [31 23]]
[[30 23]
 [30 24]]
[[30 24]
 [29 24]]
[[30 25]
 [28 24]]
[[30 26]
 [27 25]]
[[31 16]
 [30 21]]
[[31 19]
 [31 22]]
[[31 20]
 [32 23]]
[[31 21]
 [32 23]]
[[31 22]
 [32 24]]
[[31 23]
 [31 24]]
[[31 24]
 [30 25]]
[[31 25]
 [28 25]]
[[32 17]
 [31 22]]
[[32 18]
 [32 22]]
[[32 19]
 [33 23]]
[[32 20]
 [33 23]]
[[32 21]
 [33 24]]
[[32 22]
 [33 24]]
[[32 23]
 [32 25]]
[[32 24]
 [30 25]]
[[33 18]
 [34 22]]
[[33 19]
 [35 23]]
[[33 20]
 [35 24]]
[[33 21]
 [34 24]]
[[33 22]
 [33 25]]
[[33 23]
 [32 25]]
[[33 24]
 [30 25]]
[[34 19]
 [37 23]]
[[34 20]
 [36 24]]
[[34 21]
 [35 24]]
[[34 22]
 [35 25]]
[[34 23]
 [33 26]]
[[34 24]
 [31 26]]
[[34 25]
 [28 25]]
[[35 19]
 [38 23]]
[[35 20]
 [37 24]]
[[35 21]
 [37 24]]
[[35 22]
 [36 25]]
[[35 23]
 [34 26]]
[[35 24]
 [33 26]]
[[35 25]
 [30 26]]
[[35 26]
 [28 26]]
[[36 20]
 [3

 [89 67]]
[[91 67]
 [89 68]]
[[91 68]
 [89 68]]
[[91 69]
 [89 69]]
[[91 70]
 [89 70]]
[[91 71]
 [89 71]]
[[91 72]
 [90 72]]
[[91 73]
 [90 73]]
[[91 74]
 [90 74]]
[[91 75]
 [90 75]]
[[91 76]
 [91 75]]
[[91 77]
 [91 76]]
[[91 78]
 [91 77]]
[[91 79]
 [92 78]]
[[91 80]
 [92 79]]
[[91 81]
 [92 80]]
[[91 82]
 [92 81]]
[[91 83]
 [93 82]]
[[91 84]
 [93 83]]
[[91 85]
 [93 84]]
[[91 86]
 [93 85]]
[[91 87]
 [94 86]]
[[91 88]
 [94 87]]
[[91 89]
 [94 88]]
[[91 90]
 [94 89]]
[[91 91]
 [94 89]]
[[91 92]
 [95 90]]
[[91 93]
 [95 91]]
[[91 94]
 [95 92]]
[[91 95]
 [95 93]]
[[91 96]
 [95 94]]
[[91 97]
 [95 95]]
[[91 98]
 [95 96]]
[[91 99]
 [95 97]]
[[ 91 100]
 [ 96  98]]
[[ 91 101]
 [ 96  99]]
[[ 91 102]
 [ 96 100]]
[[ 91 103]
 [ 96 100]]
[[ 91 104]
 [ 96 101]]
[[ 91 105]
 [ 96 102]]
[[ 91 106]
 [ 96 103]]
[[ 91 107]
 [ 96 104]]
[[ 91 108]
 [ 97 105]]
[[ 91 109]
 [ 97 106]]
[[ 91 110]
 [ 97 107]]
[[ 91 111]
 [ 97 108]]
[[ 91 112]
 [ 97 109]]
[[ 91 113]
 [ 97 110]]
[[ 91 114]
 [ 97 111]]
[[ 91 115]
 [ 97 1

 [103 129]]
[[ 98 131]
 [103 131]]
[[ 98 132]
 [103 133]]
[[ 98 133]
 [102 134]]
[[ 98 134]
 [102 135]]
[[ 98 135]
 [102 136]]
[[ 98 136]
 [102 137]]
[[ 98 137]
 [102 138]]
[[ 98 138]
 [102 138]]
[[ 98 139]
 [102 139]]
[[ 98 140]
 [102 140]]
[[ 98 141]
 [102 140]]
[[ 98 142]
 [102 141]]
[[ 98 143]
 [102 142]]
[[ 98 144]
 [102 143]]
[[ 98 145]
 [101 144]]
[[ 98 146]
 [101 145]]
[[ 98 147]
 [101 146]]
[[ 98 148]
 [101 147]]
[[ 98 149]
 [101 148]]
[[ 98 150]
 [101 149]]
[[ 98 151]
 [101 150]]
[[ 98 152]
 [101 151]]
[[ 98 153]
 [101 152]]
[[ 98 154]
 [101 154]]
[[ 98 155]
 [100 155]]
[[ 98 156]
 [100 156]]
[[ 98 157]
 [100 157]]
[[ 98 158]
 [100 158]]
[[ 98 187]
 [100 187]]
[[ 98 188]
 [100 187]]
[[ 98 189]
 [100 188]]
[[ 98 190]
 [100 189]]
[[ 98 191]
 [100 189]]
[[ 98 192]
 [100 190]]
[[ 98 193]
 [100 191]]
[[ 98 194]
 [100 192]]
[[ 98 195]
 [100 193]]
[[ 98 196]
 [101 194]]
[[ 98 197]
 [101 194]]
[[ 98 198]
 [100 195]]
[[ 98 199]
 [100 196]]
[[ 98 200]
 [100 197]]
[[ 98 201]
 [100 197]]

 [106  68]]
[[108  65]
 [106  69]]
[[108  66]
 [106  70]]
[[108  67]
 [107  71]]
[[108  68]
 [107  72]]
[[108  69]
 [107  73]]
[[108  70]
 [107  74]]
[[108  71]
 [108  75]]
[[108  72]
 [108  76]]
[[108  73]
 [108  77]]
[[108  74]
 [109  78]]
[[108  75]
 [109  79]]
[[108  76]
 [109  80]]
[[108  77]
 [110  80]]
[[108  78]
 [110  81]]
[[108  79]
 [110  82]]
[[108  80]
 [111  83]]
[[108  81]
 [111  84]]
[[108  82]
 [111  84]]
[[108  83]
 [112  85]]
[[108  84]
 [112  86]]
[[108  85]
 [112  87]]
[[108  86]
 [112  88]]
[[108  87]
 [112  88]]
[[108  88]
 [112  89]]
[[108  89]
 [113  90]]
[[108  90]
 [113  91]]
[[108  91]
 [113  92]]
[[108  92]
 [113  92]]
[[108  93]
 [113  93]]
[[108  94]
 [113  94]]
[[108  95]
 [113  95]]
[[108  96]
 [113  96]]
[[108  97]
 [113  97]]
[[108  98]
 [114  98]]
[[108  99]
 [114  98]]
[[108 100]
 [114  99]]
[[108 101]
 [114 100]]
[[108 102]
 [114 101]]
[[108 103]
 [114 102]]
[[108 104]
 [114 103]]
[[108 105]
 [114 104]]
[[108 106]
 [114 104]]
[[108 107]
 [114 105]]

[[116  58]
 [113  61]]
[[116  59]
 [112  62]]
[[116  60]
 [112  63]]
[[116  61]
 [112  64]]
[[116  62]
 [113  66]]
[[116  63]
 [113  67]]
[[116  64]
 [113  68]]
[[116  65]
 [113  69]]
[[116  66]
 [113  70]]
[[116  67]
 [113  71]]
[[116  68]
 [113  73]]
[[116  69]
 [114  74]]
[[116  70]
 [114  75]]
[[116  71]
 [114  76]]
[[116  72]
 [115  77]]
[[116  73]
 [115  78]]
[[116  74]
 [115  79]]
[[116  75]
 [116  79]]
[[116  76]
 [116  80]]
[[116  77]
 [117  81]]
[[116  78]
 [117  81]]
[[116  79]
 [117  82]]
[[116  80]
 [117  82]]
[[116  81]
 [117  83]]
[[116  82]
 [117  84]]
[[116  83]
 [117  85]]
[[116  84]
 [118  85]]
[[116  85]
 [118  86]]
[[116  86]
 [118  87]]
[[116  87]
 [118  88]]
[[116  88]
 [118  89]]
[[116  89]
 [118  90]]
[[116  90]
 [118  91]]
[[116  91]
 [118  92]]
[[116  92]
 [118  93]]
[[116  93]
 [119  93]]
[[116  94]
 [119  94]]
[[116  95]
 [119  95]]
[[116  96]
 [119  96]]
[[116  97]
 [119  97]]
[[116  98]
 [119  98]]
[[116  99]
 [119  99]]
[[116 100]
 [119 100]]
[[116 101]


In [4]:
depthMap =cv2.imread(path+'depthMap.png',0)

In [5]:
depthMap.shape

(220, 195)

In [6]:
# Use the pixel value of the depth map directly as the depth value
newPng_origin = np.mat(np.zeros((depthMap.shape)))
for i in corresponding_in:
    newPng_origin[i[0][1],i[0][0]] = depthMap[i[1][1], i[1][0]]
    
for i in lis:
#     print(data1[int(i[0])][1],data1[int(i[0])][0])
    newPng_origin[data1[int(i[0])][1],data1[int(i[0])][0]] = depthMap[data2[int(i[1])][1], data2[int(i[1])][0]]
 
newPng_origin_array = newPng_origin.A
cv2.imwrite(path+"newPng_origin.png", newPng_origin_array)
# cv2.imwrite(path+"tps_newPng_origin.png", newPng_origin_array)

True

In [7]:
# import math
# # Converted to a depth value by a hypotenuse

# newPng_origin = np.mat(np.zeros((depthMap.shape)))
# for i in corresponding_in:
#     newPng_origin[i[0][1],i[0][0]] =math.sqrt(pow(depthMap[i[1][1], i[1][0]],2)-pow((x/2-i[1][1]),2)-pow((y/2-i[1][0]),2))
    
# for i in lis:
# #     math.sqrt(pow(depthMap[data2[int(i[1])][1], data2[int(i[1])][0]],2)-pow((x/2-data2[int(i[1])][1]),2)-pow((y/2-data2[int(i[1])][0]),2))
    
# #     newPng_origin[data1[int(i[0])][1],data1[int(i[0])][0]] = depthMap[data2[int(i[1])][1], data2[int(i[1])][0]]
#     newPng_origin[data1[int(i[0])][1],data1[int(i[0])][0]] =  math.sqrt(pow(depthMap[data2[int(i[1])][1], data2[int(i[1])][0]],2)-pow((x/2-data2[int(i[1])][1]),2)-pow((y/2-data2[int(i[1])][0]),2))
 
# newPng_origin_array = newPng_origin.A
# cv2.imwrite("newPng_origin.png", newPng_origin_array)